version: "3.4"
services:
  fiuba-course-admin-backend:
    network_mode: host
    build: .
    command: yarn pm2:start
    image: fiuba-course-admin-backend-img
    container_name: "fiuba-course-admin-backend"
    env_file:
      - .env
    ports:
      - 5006:5006
    restart: always
    depends_on:
      - fiuba-course-admin-backend-database-postgres
  fiuba-course-admin-backend-database-postgres:
    image: postgres:12.1
    container_name: fiuba-course-admin-backend-database-postgres
    volumes:
      - ./data/db:/usr/data/db
    ports:
      - 5434:5432
    restart: always
    env_file:
      - .env
