name: back-end-build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: test
    services:
      postgres:
        image: postgres:12.1
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5434:5432
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - id: nvmrc
        uses: browniebroke/read-nvmrc-action@v1
      - name: Use Node.js ${{ steps.nvmrc.outputs.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ steps.nvmrc.outputs.node_version }}
      - name: Install dependencies
        run: yarn install
      - name: Database setup
        run: yarn db:drop || true && yarn db:create && yarn db:migrate
      - name: Run linter and tests
        run: yarn lint && yarn test
      - name: Coveralls
        uses: coverallsapp/github-action@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Trigger deploy workflow
        if: success() && contains('refs/heads/staging refs/heads/production', github.ref)
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPOSITORY_DISPATCH_TOKEN }}
          repository: fiuba-course-admin/deploy
          event-type: deploy
          client-payload: '{"stage": "${{ github.ref }}", "project": "backend"}'
